// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RRHH_Backend.Domain.RRHH;

public partial class EstadoCivil
{
    public int IdestadoCivil { get; set; }

    public string Nombre { get; set; }

    public bool? RequiereConyuge { get; set; }

    public virtual ICollection<Profesores> Profesores { get; set; } = new List<Profesores>();
}