// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RRHH_Backend.Domain.RRHH;

public partial class FinanciamientoBeca
{
    public int IdFinanciamiento { get; set; }

    public string Nombre { get; set; }

    public virtual ICollection<TitulosEnCurso> TitulosEnCurso { get; set; } = new List<TitulosEnCurso>();
}