// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RRHH_Backend.Domain.RRHH;

public partial class Parroquias
{
    public int IdParroquias { get; set; }

    public int Idciudades { get; set; }

    public string Nombre { get; set; }

    public virtual Ciudades IdciudadesNavigation { get; set; }

    public virtual ICollection<Profesores> ProfesoresIdParroquiaNacimientoNavigation { get; set; } = new List<Profesores>();

    public virtual ICollection<Profesores> ProfesoresIdParroquiaResidenciaNavigation { get; set; } = new List<Profesores>();
}