// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RRHH_Backend.Domain.RRHH;

public partial class TiposContratos
{
    public int IdtiposContratos { get; set; }

    public string Nombre { get; set; }

    public int? Duracion { get; set; }

    public bool? EsAfiliado { get; set; }

    public virtual ICollection<Contratos> Contratos { get; set; } = new List<Contratos>();
}