// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RRHH_Backend.Domain.RRHH;

public partial class TipoSangre
{
    public string CodigoTipoSangre { get; set; }

    public string Grupo { get; set; }

    public bool? SitemaRh { get; set; }

    public virtual ICollection<Profesores> Profesores { get; set; } = new List<Profesores>();
}